# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HealthyDiet' do

pod 'Alamofire', '3.2'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SWXMLHash', '~> 2.3.0'
pod 'PKHUD'
pod 'SDWebImage'

end

target 'HealthyDietTests' do

end

